### ISSUE TITLE
error deploying SDN when using evaluation media

### ISSUE THREAD

**Issue by garjam73** [MicrosoftLearning/WS-013T00-Azure-Stack-HCI#3]
# Module: 4
#### Step: 07

Description of issue
when using 2019 evaluation media to create base disks the SDN creation script fails with the following error

VERBOSE: [20201203-21:55:50] Cleaning up

C:\Library\SDN-master\SDNExpress\scripts\SDNExpress.ps1 : Software Defined Networking (SDN) requires an OS

containing Windows Server 2016 Datacenter, Windows Server 2019 Datacenter, or Azure Stack HCI.

At C:\Library\Scenario_part2.ps1:257 char:1

+ . "C:\Library\SDN-master\SDNExpress\scripts\SDNExpress.ps1" -Configur ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   + CategoryInfo          : NotSpecified: (:) [SDNExpress.ps1], RuntimeException

   + FullyQualifiedErrorId : RuntimeException,SDNExpress.ps1
Repro steps:

1. create base disks using latest eval media
2. complete all lab steps in task 1 to prepare the environment
3. complete all steps in task 2 to deploy sdn in the enviromenet
4. scenarion_part2 script fails at creating SDN

**Comment by PurvesG** [comment]
There are 2 problems with the new SDNExpress scripts both in the SDNExpressModule.psm1
1.) O/S Validation fails on Evaluation version
Modify Line 2652
    ("ServerDatacenterCor", "ServerDatacenter", "ServerAzureStackHCICor") -contains $Edition.Edition)
    ("ServerDatacenterEvalCor", "ServerDatacenterCor", "ServerDatacenter", "ServerAzureStackHCICor") -contains $Edition.Edition)

2.) slbhpconfig.xml fails to generate causing the SLBHostAgent to fail on all hosts
A fix has been submitted to the SDNExpress  GitHub but has not been merged with master
There are white spaces on several lines which cause the slbhpconfig.xml to fail to create
    github.com/.../958f16874d30e9bd9c6b018506730f7890d7d252

Until the fix is merged students must edit the SDNExpressModule.psm1 before executing Scenario_Part2.ps1

To do this locate the Expand-Archive in the Scenario_Part2.ps1 execute it then REM it out
Oround Line 240
Expand-Archive -Path C:\SDN-Master.zip -DestinationPath C:\Library

Then edit the sections in the  "C:\Library\SDN-master\SDNExpress\scripts\SDNExpressModule.psm1" as above

**Comment by TJGitHubUser** [comment]
This has been fixed.

- Edits & updates to final portion of 4A instructions, both Student & LAK versions
- Added edited/fixed SDNExpressModule.psm1, placed in new /Allfiles dir for easy download.

**Comment by ojules** [comment]
Hello this issue is not resolved. I've received the below error during my observation of the Azure Stack HCI Networking lab

C:\Library\SDN-master\SDNExpress\scripts\SDNExpress.ps1 : Software Defined 
Networking (SDN) requires an OS containing Windows Server 2016 Datacenter, Windows 
Server 2019 Datacenter, or Azure Stack HCI.
At C:\Library\Scenario_Part2.ps1:256 char:1
+ . "C:\Library\SDN-master\SDNExpress\scripts\SDNExpress.ps1" -Configur ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [SDNExpress.ps1], RuntimeException
    + FullyQualifiedErrorId : RuntimeException,SDNExpress.ps1
